### ISSUE TITLE
docking

### ISSUE THREAD

**Issue by nyy777** [MolAICal/molaical.github.io#7]
Dear Dr.
I want to use  tutorial 3 for batch docking, but the following questions appear. I hope you can answer this question!Thank you 
<img width="604" alt="0eca2d71cfcaddd8464f28e5a63ce95" src="https://user-images.githubusercontent.com/92666521/162918623-844e4d51-f1e2-42c0-9e32-98e80dbd30e1.png">

**Comment by MolAICal** [comment]
> Dear Dr. I want to use tutorial 3 for batch docking, but the following questions appear. I hope you can answer this question!Thank you <img alt="0eca2d71cfcaddd8464f28e5a63ce95" width="604" src="https://user-images.githubusercontent.com/92666521/162918623-844e4d51-f1e2-42c0-9e32-98e80dbd30e1.png">

Could you compress the folder named "splitdir" to me? Then I can help you to test your problem. You can send it to my email: molaical@yeah.net

**Comment by MolAICal** [comment]
> Dear Dr. I want to use tutorial 3 for batch docking, but the following questions appear. I hope you can answer this question!Thank you 

Can you run below command and feedback output information to me (please input your install path of MolAICal):

`~/Download/MolAICal-linux64/molaicald --config conf.txt --ligand splitdir/lig_1.pdbqt --out testout.pdbqt
`

**Comment by nyy777** [comment]
The result is as follows.&nbsp;

There is no error running the command again!








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MolAICal/molaical.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MolAICal/molaical.github.io] docking (Issue #7)





  
Dear Dr. I want to use tutorial 3 for batch docking, but the following questions appear. I hope you can answer this question!Thank you
  
Can you run below command and feedback output information to me (please input your install path of MolAICal):
 
~/Download/MolAICal-linux64/molaicald --config conf.txt --ligand splitdir/lig_1.pdbqt --out testout.pdbqt

**Comment by MolAICal** [comment]
> The result is as follows.&nbsp; There is no error running the command again!
> […](#)

I guess something wrong with your ubuntu system. Could you feedback below test information to me?

1) run two commands one by one: 
`cat /proc/version`
`uname -a`

2) If you have Windows operating system, could you test tutorial 3 in your Windows operating system?

**Comment by nyy777** [comment]
&nbsp;

I tried it on windows operation systems and there was no error.Also,i tried it on linux systems again.There was no error.






-----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MolAICal/molaical.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MolAICal/molaical.github.io] docking (Issue #7)





  
The result is as follows.&nbsp; There is no error running the command again!
 …
  
I guess something wrong with your ubuntu system. Could you feedback below test information to me?
  
 
run two commands one by one:
 cat /proc/version
 uname -a
 
 
 
If you have Windows operating system, could you test tutorial 3 in your Windows operating system?

**Comment by MolAICal** [comment]
> &nbsp; I tried it on windows operation systems and there was no error.Also,i tried it on linux systems again.There was no error.
> […](#)
> -----------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MolAICal/molaical.github.io" ***@***.***&gt;; 发送时间:&nbsp;2022年4月18日(星期一) 中午1:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MolAICal/molaical.github.io] docking (Issue #7) The result is as follows.&nbsp; There is no error running the command again! … I guess something wrong with your ubuntu system. Could you feedback below test information to me? run two commands one by one: cat /proc/version uname -a If you have Windows operating system, could you test tutorial 3 in your Windows operating system? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

It seems your issue is solved. If you still have problem, you can put it on Github issue.

**Comment by nyy777** [comment]
Ok!
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MolAICal/molaical.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MolAICal/molaical.github.io] docking (Issue #7)





  
&nbsp; I tried it on windows operation systems and there was no error.Also,i tried it on linux systems again.There was no error.
 …
 -----------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MolAICal/molaical.github.io" @.&gt;; 发送时间:&nbsp;2022年4月18日(星期一) 中午1:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [MolAICal/molaical.github.io] docking (Issue #7) The result is as follows.&nbsp; There is no error running the command again! … I guess something wrong with your ubuntu system. Could you feedback below test information to me? run two commands one by one: cat /proc/version uname -a If you have Windows operating system, could you test tutorial 3 in your Windows operating system? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
It seems your issue is solved. If you still have problem, you can put it on Github issue.
