### ISSUE TITLE
Problem running molaical.exe in linux

### ISSUE THREAD

**Issue by purnawanpp** [MolAICal/molaical.github.io#8]
I have to install molaical.exe for Linux (UBUNTU 22.04) version with a tutorial from the website, but when I running molaical.exe in terminal i have a problem like this:
awk: line 1: wrong number of arguments in call to int
Invalid maximum heap size: -Xmxm
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

How to solve this problem?

**Comment by MolAICal** [comment]
> I have to install molaical.exe for Linux (UBUNTU 22.04) version with a tutorial from the website, but when I running molaical.exe in terminal i have a problem like this: awk: line 1: wrong number of arguments in call to int Invalid maximum heap size: -Xmxm Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.
> 
> How to solve this problem?

Dear user,

Do you follow the instruction [(https://molaical.github.io/install.html)](https://molaical.github.io/install.html) to install MolAICal firstly?

Best,
Qifeng Bai

**Comment by purnawanpp** [comment]
yes, I follow your instruction from this website  (https://molaical.github.io/install.html)](https://molaical.github.io/install.html).
Here the screenshot. 
![Screenshot from 2023-01-19 08-02-00](https://user-images.githubusercontent.com/77323253/213331189-bd10b38d-1a73-4d6b-8d15-6efa68e78fd1.png)

**Comment by purnawanpp** [comment]
Here proof of
![Screenshot from 2023-01-19 08-00-08](https://user-images.githubusercontent.com/77323253/213331249-9d1b8f36-a768-4185-aeab-698bea04d79b.png)
 installation

**Comment by purnawanpp** [comment]
Here proof of installation
![Screenshot from 2023-01-19 08-00-08](https://user-images.githubusercontent.com/77323253/213331304-58b30524-90e7-4759-b5d7-0d43d2bea871.png)

**Comment by MolAICal** [comment]
> Here proof of installation ![Screenshot from 2023-01-19 08-00-08]

Please put the below command in your linux console and cut the screenshot to me:
#> `locale`

**Comment by purnawanpp** [comment]
Here 
![image](https://user-images.githubusercontent.com/77323253/213373556-b57b1e9b-9a17-495a-87b1-69b722c1b1f8.png)

**Comment by purnawanpp** [comment]
Thank you its works, I run **_#> locale_** before call molaical.exe and the program runs

**Comment by purnawanpp** [comment]
Some times the programs running, and error again
![image](https://user-images.githubusercontent.com/77323253/213390595-6e53cdf7-8df4-4ac8-a85b-ec8e1781ea0d.png)

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213390807-68c772c5-964e-4c44-b62b-0c5d78bc834b.png)

**Comment by MolAICal** [comment]
> ![image]()
Dear user,

It seems you can not access much memory. Please replace 'molaical.exe' in your installed MolAICal by the below package:

**Comment by purnawanpp** [comment]
I have done it according to your suggestion but still, an 
![Screenshot from 2023-01-20 13-46-28](https://user-images.githubusercontent.com/77323253/213634866-98dfc3da-fe60-40b5-a338-9cfa1ed72e53.png)
error like this.

**Comment by MolAICal** [comment]
> 
Could you try the below package, and give me a screenshot?
[molaical.zip](https://github.com/MolAICal/molaical.github.io/files/10464121/molaical.zip)

**Comment by purnawanpp** [comment]
still error: 
molaical.exe
awk: line 1: wrong number of arguments in call to int

Invalid maximum heap size: -Xmxm
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by MolAICal** [comment]
> still error: molaical.exe awk: line 1: wrong number of arguments in call to int
> 
> Invalid maximum heap size: -Xmxm Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.

Probably, something wrong is in your current ubuntu system, please give me screenshots by two below commands:
#> `cat /proc/meminfo`
#> `free -m`

**Comment by purnawanpp** [comment]
![Screenshot from 2023-01-20 15-18-50](https://user-images.githubusercontent.com/77323253/213648693-bc6ab128-3429-48d5-aa93-abdb89682e0f.png)
![Screenshot from 2023-01-20 15-18-23](https://user-images.githubusercontent.com/77323253/213648697-d38eeb35-dbba-4056-9cff-e85dfaa7f994.png)
I have tried using two computers with lubuntu 20.04 operating system, but they produce the same error. I have tried the molaical.exe software on the Windows operating system, which can run smoothly. I switched to the Windows operating system only; thank you for developing the software. Your software is very useful in our lab.

**Comment by MolAICal** [comment]
>

Please try the below package, and give me screenshot (not copy fonts)! I think some operations are wrong because I do not see any output.
[molaical.zip](https://github.com/MolAICal/molaical.github.io/files/10464573/molaical.zip)

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213653136-4043373f-ab90-44f8-a60a-1b14f03e208a.png)
it is work thank you. 
![image](https://user-images.githubusercontent.com/77323253/213653414-07382fe5-f225-4ee9-9a67-65b95a74498f.png)
Do you think there is something wrong with my computer or operating system?

**Comment by MolAICal** [comment]
> probably, you can input below command, and give me a screenshot, then I can check whether something is wrong in your operation system:
#> `awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo`

**Comment by MolAICal** [comment]
> 

probably, you can input below command, and give me a screenshot, then I can check whether something is wrong in your operation system:
#> awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213657363-c23b74e1-4a2b-46ce-84ba-7b363d2d45c6.png)
here.

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213658748-77bced5d-f7db-4ed9-b50d-36f8c393eff8.png)

**Comment by MolAICal** [comment]
> 
sorry, please input these below commands, and give me screenshot:
#> `Total=$(awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo)`
#> `memUse=$(echo | awk "{print int($Total * 0.5)}")`
#> `echo $memUse`

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213659542-1d0b1b51-57e1-44fd-bbbb-1047827de692.png)

**Comment by MolAICal** [comment]
> 
sorry, I forgot to let you ouput Total, please input these below commands, and give me screenshot again:
#> `Total=$(awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo)`
#> `echo $Total`
#> `memUse=$(echo | awk "{print int($Total * 0.5)}")`
#> `echo $memUse`

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/213660883-61557e98-a90d-4123-bfe4-bc539b6f6be8.png)

**Comment by MolAICal** [comment]
>
Could you input the test commands, and give me screenshot again? Thanks.
#> `Total=$(awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo)`
#> `echo $Total`
#> `memUse=$(echo | awk "{print ($Total * 0.5)}")`
#> `echo $memUse`

**Comment by purnawanpp** [comment]
I'm sorry, Monday I'll try again. thank you

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/214199501-3f063bb6-2186-41b7-9fd7-a9d2e9c00e68.png)

**Comment by MolAICal** [comment]
> !
Thanks for your feedback. Based on the results, I guess your ubuntu default language may be Indonesia rather than pure English. So some syntax cannot be recognized. To make further fix this problem, please input the below commands, and give me screenshot, I think it soon solve this issue based on this feedback:
`Total=$(LC_NUMERIC=C awk '/MemTotal/{total=$2}/MemAvailable/{free=$2}END{print (free)/1024}'  /proc/meminfo)
echo $Total
memUse=$(echo | LC_NUMERIC=C awk "{print int($Total * 0.5)}")
echo $memUse
`

**Comment by purnawanpp** [comment]
![image](https://user-images.githubusercontent.com/77323253/214220443-a6a8cf59-46ef-47b6-886f-8eff9842fc5e.png)

**Comment by MolAICal** [comment]
>
Now, MolAICal-linux version has solved your problem, you can choose anyone below solution:
1) download Development version from [https://molaical.github.io/](https://molaical.github.io/)
2) replace molaical.exe from the attachment:  [molaical.zip](https://github.com/MolAICal/molaical.github.io/files/10486802/molaical.zip)

**Comment by purnawanpp** [comment]
What a thoughtful software. I really appreciate this.
